require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable

Style/Documentation:
  Enabled: false
  EnforcedShorthandSyntax: either

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'path', 'xdescribe']

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/api/v1/*

Style/HashSyntax:
  EnforcedShorthandSyntax: either

RSpec/VariableName:
  Exclude:
    - spec/requests/api/v1/*
