require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable
  inherit_mode: merge

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'path', 'xdescribe', 'post', 'context', 'it', 'let']

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/api/v1/*

Style/HashSyntax:
  EnforcedShorthandSyntax: either

RSpec/VariableName:
  Exclude:
    - spec/requests/api/v1/*

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - response
        - run_test

RSpec/MultipleMemoizedHelpers:
    Max: 10

RSpec/MultipleExpectations:
    Max: 2
