default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= Rails.application.credentials.dig(:database_name) %>
  url: <%= Rails.application.credentials.dig(:database_url) %>
  host: <%= Rails.application.credentials.dig(:database_host) %>
  username: <%= Rails.application.credentials.dig(:database_username) %>
  password: <%= Rails.application.credentials.dig(:database_password) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
