default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['POSTGRES_DB'] || Rails.application.credentials.dig(:database_name) %>
  host: <%= ENV['POSTGRES_HOST'] || Rails.application.credentials.dig(:database_host) %> 
  username: <%= ENV['POSTGRES_USER'] || Rails.application.credentials.dig(:database_username) %>
  password: <%= ENV['POSTGRES_PASSWORD'] || Rails.application.credentials.dig(:database_password) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
